eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: projects-service
  data:
    web:
      sort:
        sort-parameter: creation_date
      pageable:
        default-page-size: 5
        max-page-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projects_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1}
  flyway:
    baseline-on-migrate: true

application:
  title: Projects Management Application
  description: Application for projects and tasks managing
  version: 1.0
server:
  port: 0







