version: "3.3"
services:
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:management
    ports:
       - "5672:5672"
       - "15672:15672"
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "projects_management"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    ports:
      - "5432:5432"



