create table users
(
    id         int8 generated by default as identity,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    role       varchar(255),
    primary key (id)
);
create table projects
(
    id             int8 generated by default as identity,
    active         boolean not null,
    creation_date  date,
    customer       varchar(255),
    dead_line_date date,
    description    varchar(2048),
    name           varchar(255),
    title          varchar(255),
    primary key (id)
);

create table projects_employees
(
    project_id  int8 not null,
    employee_id int8 not null,
    primary key (project_id, employee_id)
);

create table tasks
(
    id             int8 generated by default as identity,
    active         boolean not null,
    creation_date  date,
    dead_line_date date,
    description    varchar(2048),
    title          varchar(255),
    project_id     int8,
    primary key (id)
);

create table tasks_employees
(
    task_id     int8 not null,
    employee_id int8 not null,
    primary key (task_id, employee_id)
);

alter table if exists projects
    add constraint projects_name unique (name);
alter table if exists projects_employees
    add constraint projects_employees_fk foreign key (employee_id) references users;
alter table if exists projects_employees
    add constraint employees_projects_fk foreign key (project_id) references projects;
alter table if exists tasks
    add constraint projects_tasks_fk foreign key (project_id) references projects;
alter table if exists tasks_employees
    add constraint tasks_employees_fk foreign key (employee_id) references users;
alter table if exists tasks_employees
    add constraint employees_tasks_fk foreign key (task_id) references tasks;