jwt:
  accessTokenSecret: salam
  refreshTokenSecret: aleykum
  refreshTokenExpirationDays: 30
  accessTokenExpirationMinutes: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: authentication-service
server:
  port: 0

redis:
  host: localhost
  port: 6379








