server:
  port: 8081
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF