package com.strigalev.starter.model;

public enum UserAction {
    LOGOUT,
    SIGN_IN,
    SIGN_UP,
    REQUEST_RESET_PASSWORD,
    RESET_PASSWORD,
    CREATE_PROJECT,
    UPDATE_PROJECT,
    UPDATE_TASK,
    DELETE_PROJECT,
    DELETE_TASK,
    ADD_TASK_TO_PROJECT,
    ADD_USER_TO_PROJECT,
    ASSIGN_TASK_TO_USER,
    OPEN_TASK,
    UNASSIGN_TASK_TO_USER,
    TAKE_TASK_FOR_DEVELOPING,
    COMPLETED_TASK,
    TAKE_TASK_FOR_TESTING,
    COMPLETED_TASK_TESTING,
    SET_TASK_DOCUMENTED,
}
